name: Sync from Public Repo

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch from public repository
        run: |
          echo "添加公共仓库作为远程源..."
          git remote add public https://github.com/joey-zhou/xiaozhi-esp32-server-java.git
          git fetch public main

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD public/main; then
            echo "没有检测到新的更改"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "检测到公共仓库有新的更改"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Merge changes from public main
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          echo "尝试合并公共仓库的更改..."
          # 尝试合并，如果有冲突则中止
          if git merge public/main --no-commit --no-ff; then
            # 检查是否有需要提交的更改
            if git diff --staged --quiet; then
              echo "合并成功，但没有需要提交的更改"
            else
              echo "合并成功，提交更改..."
              git commit -m "Merge changes from public repository (PR同步)"
              git push origin main
            fi
            echo "成功将公共仓库的更改同步到私有仓库"
          else
            echo "检测到合并冲突。需要手动处理。"
            git status
            git merge --abort
            exit 1
          fi
      
      - name: No changes needed
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "公共仓库没有新的更改，无需同步"